config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'projects/:id', to: 'projects#show', as: :project
  get 'projects', to: 'projects#index', as: :projects
  post 'projects/:id/comment', to: 'projects#comment', as: :project_comment
  delete 'projects/:id/comment/:comment_id', to: 'projects#delete_comment', as: :projects_comment

  get 'home/show'
  get 'signin', to: 'sessions#new', as: :signin
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy', as: :signout

  get 'signup', to: 'registrations#new'
  post 'signup', to: 'registrations#create'

  resources :users
  namespace :admin do
    resources :projects
  end

  root 'home#show'
end

app/models/project.rb
class Project < ApplicationRecord
  include Tivity::Activise
  has_many :comments

  activities create: true, update: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :ensure_logged_in
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to admin_project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :status)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :ensure_logged_in

  def show
    @project = Project.includes(activities: [:user, { activised: :user }]).find(params[:id])
  end

  def index
    @projects = Project.all
  end

  def delete_comment
    comment = Comment.find(params[:comment_id])

    respond_to do |format|
      if comment.destroy

        format.turbo_stream do
          render turbo_stream: turbo_stream.remove(view_context.dom_id(comment.activity))
        end
        format.html { redirect_to project_url(project) }
      else
        render 'show'
      end
    end
  end

  def comment
    project = Project.find(params[:id])

    comment = project.comments.new(comment_params.merge({ user_id: current_user.id }))

    respond_to do |format|
      if comment.save
        activity = comment.activity

        format.turbo_stream do
          result = [
            turbo_stream.append(:activities, partial: 'projects/associated_activity',
                                             locals: { project:, a: activity }),
            turbo_stream.replace(:'comment-form', partial: 'projects/comment_form', locals: { project: })
          ]

          render turbo_stream: result
        end
        format.html { redirect_to project_url(project) }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :project_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_activity.html.erb
<div id="<%= dom_id(a) %>" class="flex flex-col bg-green-200 p-4  comment-time">
  <div class="font-bold mb-4"><%= a.activiable_type %> was <%= a.operation %>d</div>
  <% a.diff && a.diff.each do |property, (from,to)| %>
    <div class="ml-4">
      Changed <span class="text-bold"><%= property %></span> from <%= from %> to <%= to %>
    </div>
  <% end %>
  <div class="flex justify-between mt-4">
    <%= a.user.email %>
    <div class="text-xs pt-1"><%= a.created_at&.to_formatted_s(:long_ordinal) %></div>
  </div>
</div>

app/views/projects/_associated_activity.html.erb
<div id="<%= dom_id(a) %>" class="flex flex-col bg-green-200 p-4 comment-time">
  <div class="font-bold"><%= a.activised_type %> was <%= a.operation %>d</div>
  <div class="italic p-4 bg-white"><%= a.activised.body %></div>
  <div class="flex justify-between mt-4">
    <%= a.user.email %>
    <div class="text-xs pt-1"><%= a.created_at&.to_formatted_s(:long_ordinal) %></div>
  </div>
  <div class="">
    <%= button_to 'Delete', projects_comment_path(project.id, a.activised.id), method: 'delete', scope: 'comment', class: 'bg-slate-500 py-2 px-4 rounded' if a.activised.user == current_user%>
  </div>
</div>

app/views/projects/_comment_form.html.erb
<%= form_with scope: 'comment', url: project_comment_path(project), local: false do |f| %>
  <%= f.text_field :body  %>
  <%= f.hidden_field :project_id %>
  <%= f.submit 'Comment', class: 'rounded px-3 py-2 bg-indigo-400 m-2' %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= project.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= project.status %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="w-1/2">
  <h1 class="font-bold text-4xl mb-10">Projects</h1>
  <div class="flex flex-col gap-y-6">
    <% @projects.each do |project| %>
      <div class="bg-blue-100 w-full p-4">
        <div class="flex justify-between">
          Name:
          <h2 class="text-lg"><%= project.name %></h2></div>
        <div class="flex justify-between">
          Status:  
          <div><%= project.status %> </div>
        </div>
        <%= link_to "Show", project, class: 'inline-block px-6 py-2 rounded bg-indigo-600' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div>
  <h1 class="text-4xl">Project <span class="text-slate-600 text-thin"><%= @project.name %></span></h1>
  <div class="mt-6">
    Status: 
    <%= @project.status %>
  </div>
  <div id="activities" class="flex flex-col gap-4">
    <% @project.activities.each do |a| %>
      <% if a.activised_type.present? %>
        <%= render partial: 'projects/associated_activity', locals: {project: @project, a: a} %>
      <% else %>
        <%= render partial: 'projects/activity', locals: {a: a} %>
      <% end %>
    <% end %>
  </div>

  <div>
    <div data-controller="comments">
      <div class="inline-block rounded bg-indigo-400 px-4 py-2" data-action="click->comments#newComment" >
        Create a new Comment
      </div>
      <div data-comments-target="form" class="invisible js-toggle-comment-form bg-slate-200 p-8">
        <div id="comment-form" class='form'>
          <%= render partial: 'projects/comment_form', locals: { project: @project } %>
        </div>
      </div>
    </div>
  </div>
</div>